Default: &defaults
  database: KarlPersonal.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: KarlPersonal_test.sqlite3
  <<: *defaults

Staging:
  database: KarlPersonal_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: KarlPersonal_production.sqlite3
  poolsize: 100
  <<: *defaults
